/*! Adjust names in a backend module to ensure they're distinct and valid.

A [`naga::ir::Module`] is allowed to use whatever names it likes for
functions, types, variables, and so on, regardless of whether they are
reserved words in some language, or even if they are unique. This
works because the names in a `Module` are not load-bearing: all
references use handles to identify their referents, not name lookup.
(Entry point names are the exception, as they appear in pipeline
descriptors.)

But once we generate target shader language code, the names become
load-bearing again. To ensure that backends can simply trust the names
they're given in the backend IR, a completed [`back::ir::Module`] is
guaranteed to use only legal identifier names that are distinct within
their relevant scopes.

This module defines [`ModuleBuilder::adjust_names`], a function
that makes a pass over the backend `Module` and ensures that each name
is a legal identifier in the target language, and distinct as
necessary within its scope.

[`naga::ir::Module`]: crate::ir::Module

 */

use crate::back;
use back::ir::builder::ModuleBuilder;
use back::ir::option::NamingRules;

use alloc::vec::Vec;

impl ModuleBuilder {
    /// Ensure all items in `self.module` are named by legal, unshadowed identifiers.
    ///
    /// Assign names to all functions, variables, types, etc. in `module` such
    /// that each identifier is valid according to `rules`, and each reference
    /// resolves to the correct definition, taking `module`'s handles as
    /// authoritative. Items like types that can be written with
    /// their own syntax may be left unnamed.
    ///
    /// Initially, `module` may contain anonymous items (generated by the SPIR-V
    /// front end, say), or items with duplicate names (introduced by lowering,
    /// say). By the time this function returns, all items will have usable
    /// names, regardless.
    ///
    /// Make a reasonable effort to use the original names (when available). If
    /// that is not possible, the adjusted names should be based on the original
    /// names.
    ///
    /// Note that although [`Function::name`] is adjusted, [`EntryPoint::name`]
    /// is not. Entry point names are the means by which the user selects the
    /// entry points to use when creating a pipeline; changing them would break
    /// the user's code. However, in principle, the user has no idea what
    /// language we're translating their shaders into, so we cannot assume that
    /// their chosen entry point names are even valid identifiers in our target
    /// language. Backends must be prepared for [`Function::name`] and
    /// [`EntryPoint::name`] to be different, and perhaps provide a mapping from
    /// the user's chosen names to the actual names used in the translated
    /// module.
    pub fn adjust_names(&self, rules: &NamingRules) {
        // todo!()
    }
}
