/*! Adjust names in a backend module to ensure they're distinct and valid.

A [`naga::ir::Module`] is allowed to use whatever names it likes for
functions, types, variables, and so on, regardless of whether they are
reserved words in some language, or even if they are unique. This
works because the names in a `Module` are not load-bearing: all
references use handles to identify their referents, not name lookup.
(Entry point names are the exception, as they appear in pipeline
descriptors.)

But once we generate target shader language code, the names become
load-bearing again. To ensure that backends can simply trust the names
they're given in the backend IR, a completed [`back::ir::Module`] is
guaranteed to use only legal identifier names that are distinct within
their relevant scopes.

This module defines [`back::ir::ModuleContext::adjust_names`], a function
that makes a pass over the backend `Module` and ensures that each name
is a legal identifier in the target language, and distinct as
necessary within its scope.

We assume validation Entry point names are assumed to be distinct and legal identifiers


[`naga::ir::Module`]: crate::ir::Module

*/

use crate::back;

use alloc::vec::Vec;

impl<'m> back::ir::ModuleContext<'m> {
    /// Ensure all items in `out` are named by legal, unshadowed identifiers.
    ///
    /// Assign names to all types, functions, variables, ... in `out` such that
    /// each identifier is valid according to `self.options.naming_rules`, and
    /// each reference resolves to the correct definition, taking `out`'s
    /// handles as authoritative.
    ///
    /// Initially, `out` may contain anonymous items (generated by the SPIR-V
    /// front end, say), or items with duplicate names (introduced by lowering,
    /// say). By the time this function returns, all items will have usable
    /// names, regardless.
    ///
    /// Make a reasonable effort to use the original names (when available). If
    /// that is not possible, the adjusted names should be based on the original
    /// names.
    pub fn adjust_names(&self, out: &mut back::ir::Module) {
        // todo!()
    }
}
